# ======
# Project Details
# ======

name: {{ project.name }}
profile: {{ project.profile_name }}
config-version: 2
version: '1.0'
require-dbt-version: ">=0.16.0"

# ======
# File Path Configs
# ======
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# ======
# Vars & Settings
# ======

quoting:
  database: false
  identifier: false
  schema: false

# ======
# Run Hooks
# ======

# on-run-start:
#  - "{{ grant_select_on_schemas(schemas, ['transformer','reporter']) }}"

# on-run-end:
#  - "{{ grant_select_on_schemas(schemas, 'reporter') }}"
#  - "{{ grant_select_on_schemas(schemas, 'transformer') }}"

# ======
# Seed Configs
# ======
    # Full documentation: https://docs.getdbt.com/reference/seed-configs/
    # (use for importing csv's of re-used items <example mcc code definitions> )
seeds:
  quote_columns: false


# ======
# Model Configs
# ======
# Full documentation: https://docs.getdbt.com/reference/model-configs

models:
  transient: true
  # -- change this to your project name --
  {{ project.name }}:
    staging_tables:
        +enabled: true
        +schema: stage
    # applies to all files under models/star_schema:
    modeled_star:
        +enabled: true
        +schema: star
    # Applies to all files under models/denorm_schema:
    modeled_denorm:
        +enabled: true
        +schema: denorm
        +materialized: view
    # Applies to all files under models/marts:
    modeled_marts:
        +enabled: true
        +schema: mart

# ======
# Package Source Configs
# ======

# ======
# Snapshot Configs
# ======
